- src: http://github.com/websoft9dev/role_common

- src: http://github.com/websoft9dev/role_cloud

- src: http://github.com/websoft9dev/role_ruby
  
- src: http://github.com/websoft9dev/role_redis

- src: http://github.com/websoft9dev/role_apache

- src: http://github.com/websoft9dev/role_passenger
  
- src: http://github.com/websoft9dev/role_nodejs

- src: http://github.com/websoft9dev/role_docker
  
- src: http://github.com/websoft9dev/role_postgresql

- src: http://github.com/websoft9dev/role_init
  
- src: http://github.com/websoft9dev/role_preend

- src: http://github.com/websoft9dev/role_end
