# external Dependencies Installation
- name: Install external dependency
  apt: 
    name: [zlib1g-dev,libxml2-dev,libsqlite3-dev,libpq-dev,libxmlsec1-dev]
    update_cache: yes

# install Passenger + Apache module
- name: Install Passenger + Apache dependencies
    shell: 
      sudo apt-get install -y dirmngr gnupg
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
      sudo apt-get install -y apt-transport-https ca-certificates
      sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bionic main > /etc/apt/sources.list.d/passenger.list'
      sudo apt-get update
      sudo apt-get install passenger libapache2-mod-passenger apache2
      sudo apt-get update
      sudo apt-get upgrade
      
      





