# using git clone canvas
- name: Install git
  shell:  apt install git

- name: Clone Canvas
  shell: |
    git clone https://github.com/instructure/canvas-lms.git canvas
  args:
    cmd:  git checkout stable
    chdir: canvas

# external Dependencies Installation
- name: Install dependency
  apt: 
    name: software-properties-common , repository , ppa:brightbox/ruby-ng , zlib1g-dev , libxml2-dev ,  libsqlite3-dev , libpq-dev , libxmlsec1-dev , curl , make , g++
    update_cache: yes

- name: Install Canvas dependencies1
  shell: |
  args:
    cmd: bundle install
    chdir: canvas

# Sometimes you have to run this command twice if there is an error
- name: Install Canvas dependencies2
  shell: |
    yarn install --pure-lockfile
    yarn install --pure-lockfile


