# external Dependencies Installation
- name: Install external dependency
  apt: 
    name: [zlib1g-dev,libxml2-dev,libsqlite3-dev,libpq-dev,libxmlsec1-dev,acl]
    update_cache: yes
      
      





