

# Canvas ownership
- name: Set Canvas ownership
  shell: |
    adduser --disabled-password --gecos canvas canvas 
    chown canvas config/*.yml
    sudo chmod 640 config/*.yml
  args:
    chdir: /data/wwwroot/canvas

# Apache Configure
- name: Copy VirtualHosts file with owner and permissions
  copy:
    src:  canvas.conf
    dest: /etc/httpd/conf.d/vhost.conf

- name: Restart Apache
  service:
    name: apache
    state: restarted
    enabled: yes
    
# Optimizing File Downloads
- name: Set mod_xsendfile for optimizing file downloads
  copy:
    src:  production-local.rb
    dest: /data/wwwroot/canvas/config/environments/production-local.rb

# Cache configuration
- name: Set Redis of Cache configuration
  shell: |
    cp config/cache_store.yml.example config/cache_store.yml
    cp config/redis.yml.example config/redis.yml
  args:
    chdir: /data/wwwroot/canvas

# Install QTIMigrationTool
- name: Install QTIMigrationTool
  shell: |
    cd /data/wwwroot/canvas/vendor
    git clone https://github.com/instructure/QTIMigrationTool.git QTIMigrationTool
    cd QTIMigrationTool
    chmod +x migrate.py
    
# Automated jobs
- name: Setting canvas_init service
  copy:
    src: canvas_init.service
    dest: /lib/systemd/system/canvas_init.service
    
- name: Start and enable canvas_init.service
  service:
    name: canvas_init
    state: started
    enabled: yes

# check version
- block:
  - name: Check Canvas Version
    shell: sudo sh -c "echo 'no method for canvas version' 1>> /data/logs/install_version.txt"
