




    


# Cache configuration
- name: Set Redis of Cache configuration
  shell: |
    cp config/cache_store.yml.example config/cache_store.yml
    cp config/redis.yml.example config/redis.yml
  args:
    chdir: /data/wwwroot/canvas

# Install QTIMigrationTool
- name: Install QTIMigrationTool
  shell: |
    cd /data/wwwroot/canvas/vendor
    git clone https://github.com/instructure/QTIMigrationTool.git QTIMigrationTool
    cd QTIMigrationTool
    chmod +x migrate.py
    
# Automated jobs
- name: Setting canvas_init service
  copy:
    src: canvas_init.service
    dest: /lib/systemd/system/canvas_init.service
    
- name: Start and enable canvas_init.service
  service:
    name: canvas_init
    state: started
    enabled: yes

# check version
- block:
  - name: Check Canvas Version
    shell: sudo sh -c "echo 'no method for canvas version' 1>> /data/logs/install_version.txt"

  - name: Check canvas_init Service
    shell: systemctl status canvas_init | grep Active*
    register: check_canvas_init_service
    notify: check_canvas_init_service