# install Canvas by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure Canvas
- block:
  - name: Configure Canvas
    shell: |
      for config in amazon_s3 delayed_jobs domain file_store outgoing_mail security external_migration; \
          do cp -v config/$config.yml.example config/$config.yml; done 
      cp config/dynamic_settings.yml.example config/dynamic_settings.yml
      bundle exec rails canvas:compile_assets
    args:
      chdir: canvas/

- block: 
  - name: SQL configure
    shell: | 
      cp config/database.yml.example config/database.yml
      createdb canvas_development


# set soft link, -f enforce the exist links
# ln -sf src des
#- name: set soft link
#  shell: |
    

# Check version,
# must use sudo sh -c to solve the no-root permission
#- block:
#  - name: Check Canvas Version
#    shell: sudo sh -c " 1>> /data/logs/install_version.txt"


# check service state
- name: Check Canvas Service
  shell: systemctl status canvas | grep Active*
  register: check_canvas_service
  notify: check_canvas_service
